### ISSUE TITLE
Scroll 

### ISSUE THREAD

**Issue by Textras** [BeMyEye/cordova-plugin-googlemaps#5]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

Hi. So we also forked and modified this plugin for some of our own performance reasons, and reviewing that very long thread I hope all understand that the beautiful thing about open source is doing just that. The main plugin is tremendous work and it seems here you are taking it in an entirely different direction and both are absolutely ok.

One of the critiques you had was the scrolling and I might differ from a 'nobody wants this perspective'. Particularly in a feed or a chat etc there are lots of reasons why one might want this. Do you have any suggestions if we were to do this in our fork, or any modifications you could do to include it here? 

We plan to try this fork and watch closely just to see where it goes and the direction you take it. Hoping for a good outcome for all, and offer appreciation to ALL those who have helped and performed the heavy lifting on it, in the past and future.

**Comment by Textras** [comment]
I should mention that we don't destroy the map, nor do we have multiple maps in our implementation. The former recommended as standard practice if I'm not mistaken. The transition to map caused significant flicker and delay via this destroy method in our implementation so we now persist it. Also our fork we changed the setInterval function that was pinging the DOM for positioning at an insane rate, which we now disable after 500ms or so. Again we may (and likely will) add multiple maps in future and are trying to figure out how that could work logistically now.

**Comment by cvaliere** [comment]
hello @Textras 

I'll try to make the most complete answer I can :)

1st, I think a scrolling map is not so good in a mobile app, because when you're scrolling and suddenly there's a map in the scroll, your scrolling movement gets intercepted by the map, and it's very annoying, especially on a small screen like a smartphone. But this is personal opinion and you can want a scrolling map anyway :)

2nd, the fact is, it's impossible to achieve with any hybrid framework. The official plugin tries to achieve it, and as explained in my README, it fails at it. Except if you're not ashamed in having your map jumping and bouncing around, joyfully overlapping the rest of your html page...

In the end, our approach was to totally remove everything automatic from the plugin. So, whenever your map, or any HTML element *on top of your map* changes position, you have to tell the plugin with our new method updateDomPositions(mapDiv).

To achieve a scrolling map, you could add a listener on your scroll, and call updateDomPositions from it. We didn't try, but it could work, actually :)

Just for information, multiple maps work very well, with the official plugin, and with this fork also. Note that every map takes a significant amount of memory (~100M), so if you're keeping one in memory, it's ok, but if you use multiple maps, you'll probably want to keep only your "main" map in memory, and destroy the others.

**Comment by cvaliere** [comment]
I've updated our fork with new improvements (everything is described in the README). Now, I think that my refactoring is finished.

To achieve a scrolling map, you now just have to call map.refreshLayout(). The frequency is up to you, I didn't test it.

If you test it and you're happy with it, please let me know

**Comment by fssrepository** [comment]
I have read some of your comments, i forked your repo, not to create a new one, just play with it.
Unfortunately i share your thoughts about code quality, i haven't seen a totally working repo, but i have looked at hundreds of plugins. I was hesitating to jump to native development, i might not have the capacity to really work on this repo, but to be honest, i have a project called fms on my repo, where i'm going to rethink the whole map solution. I would further reduce the functionality.

To be honest Google earns a lot you to be able to show some dots on the map without anything.

I think the 95% of income is coming only that you have been forced to use the api, instead of embedded or anything static, because you need to set latitude and longitude to your pins, and for most of the site is enough.

Other thing is, i made some styling on google javascript popup window, but i realized that the best way to show info if you have only one element at the top of the map. (I made there a scrollbar, when you click on one of the item it's showing the location, when you click on the pin it's scrolling to the info)

I have recreated the ionic framework as i found it very buggy, and i have focused on how to reduce the bundle size. Initially it was 2,8MB javascript zipped, which did go to 482KB, and can go further.

I have made a virtual scroll, which is smooth, but i have realized that even just some fancy button on the screen, or not using sprite definitely kills the performance.

You need to avoid dom manipulation on scrolling, you need to use translateX which is using the device hardware. I need to dig in a little bit to this mapping concept, but i have experienced that if you have only images in a scroll will be smooth, anything else should be disappeared at the right time.

If you need scrolling map, i would sniff it into a canvas and scroll the image only. :) Took me weeks to create a smooth scrolling performance, and i haven't finished yet, as with translateX you need to emulate some negative value to scroll up in a never ending list and so on. At the moment which scrolls elements with variable height does not exist in the universe.

To be honest what i realized as a big problem with this map, very likely somebody would like to use a the javascript api next to it, but this library is massive 250KB unzipped / unminified with several files which kills the loading time with the delays and the cordova is unfortunatelly taking stupidly the www folder even if the plugin does not support the browser version (Other thing, even if it's in an apk, i realized that it does matter whether one file will be loaded from the disk or several - (Xperia z3 compact also can see the difference)). I'm missing some fallback from the code, and i'm not sure why this library is so big, it seems to me re-implementing the whole google javascript api.

**Comment by Textras** [comment]
Yes thank you @cvaliere for that great response.

We will give some exploratory testing and get back to you. In our situation, the scrolling pertains to live location sharing so the map would dynamically update inside a msg bubble, which is obviously inside a scrollable chat. Something that could be handled in a far less eloquent way via a static map representation that requires a tap, which is far less than ideal. Will have a peruse over the readme tonight. Also sorry for the delay. Hectic week. Thanks again.

**Comment by cvaliere** [comment]
should I close this issue?
